### ISSUE TITLE
Maintain db2fog

### ISSUE THREAD

**Issue by misteral** [yob/db2fog#15]
@yob hi,  [ITBeaver](https://github.com/itbeaver/) can maintain this gem. 
RubyGems profile: https://rubygems.org/profiles/itbeaver  
fork: https://github.com/itbeaver/db2fog

---

al, CTO ITBeaver

**Comment by yob** [comment]
Cheers! I've added you as a maintainer on [rubygems.org](https://rubygems.org/gems/db2fog).
